# Generated by Django 5.2 on 2025-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('transcription', models.CharField(blank=True, default='',
                                                   max_length=100, verbose_name='Транскрипция')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('examples', models.TextField(blank=True, verbose_name='Примеры')),
            ],
        ),
    ]
